import { options } from "@/app/_clients/nextAuth";
import { AuthProvider } from "@/app/_providers/AuthProviders";
import AuthNavBar from "@/components/molecules/AuthNavBar";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import type { PropsWithChildren, ReactNode } from "react";

export const metadata: Metadata = {
  title: "Project Management",
  description: "Generated by create next app",
};

const items = [
  { title: "Project", href: "/project" },
  { title: "Task", href: "/task" },
  { title: "Event", href: "/event" },
];

type Props = PropsWithChildren<{
  children: ReactNode;
}>;

export default async function SiteLayout({ children }: Props) {
  const session = await getServerSession(options);
  return (
    <AuthProvider>
      <AuthNavBar logo={"App"} items={items} session={session} />
      {(session?.user && (
        <main className="py-4 px-8 flex-1 overflow-y-auto">{children}</main>
      )) || <div className="p-4">no session</div>}
    </AuthProvider>
    // {dialog}
  );
}
