import { AuthProvider } from "@/app/_providers/AuthProviders";
import { NavBar } from "@/components/molecules/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { PropsWithChildren, ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const items= [
  { title: "Home", href: "/taxonomy" },
  { title: "About", href: "/about" },
  { title: "Contact", href: "/contact" },
];

type Props = PropsWithChildren<{
  dialog: ReactNode;
}>;

export default function DashboardLayout({ dialog, children }: Props) {
  return (
    <html lang="en">
      <body
        className={[
          inter.className,
          "bg-gray-700 text-gray-200 h-screen flex flex-col",
          // for dialog
          "has-[dialog[open]]:overflow-hidden",
        ].join(" ")}
      >
        <AuthProvider>
          {/* <Header /> */}
          <NavBar items={items} />
          <main className="py-4 px-8 flex-1 overflow-y-auto">{children}</main>
        </AuthProvider>
        {dialog}
      </body>
    </html>
  );
}
