export const themes = [
  {
    id: "1",
    title: "テーマ 1",
    company: "A社",
    companyId: 1,
    assignee: "User 1",
    status: "In Progress",
  },
  {
    id: "2",
    title: "テーマ 2",
    company: "A社",
    companyId: 1,
    assignee: "User 2",
    status: "In Progress",
  },
  {
    id: "3",
    title: "テーマ 3",
    company: "",
    companyId: 2,
    assignee: "User 3",
    status: "To Do",
  },
  {
    id: "4",
    title: "テーマ 4",
    company: "B社",
    companyId: 2,
    assignee: "User 4",
    status: "Done",
  },
  {
    id: "5",
    title: "テーマ 5",
    company: "B社",
    companyId: 2,
    assignee: "User 5",
    status: "To Do",
  },
];
