import { getServerSession } from "@/app/_clients/nextAuth";
import { AuthProvider } from "@/app/_providers/AuthProviders";
import AuthNavBar from "@/components/molecules/AuthNavBar";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import type { PropsWithChildren, ReactNode } from "react";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const items = [{ title: "Sample", href: "/sample" }];

type Props = PropsWithChildren<{
  children: ReactNode;
}>;

export default async function SiteLayout({ children }: Props) {
  const session = await getServerSession();
  return (
    <AuthProvider>
      <div className="flex flex-col h-screen">
        <AuthNavBar logo={"App"} items={items} session={session} />
        <main className="flex-1 px-4">{children}</main>
      </div>
      <Toaster />
    </AuthProvider>
    // {dialog}
  );
}
